name: shuttlers_live_chat
description: Live Trip Chat SDK for Shuttlers Assesment
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.7.2

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^3.1.0
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  retry: ^3.1.2
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
